export const SUCCESSFULL_REGISTRATION = 'SUCCESSFULL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CLEAN_ALERT = 'CLEAN_ALERT';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
