export const SUCCESSFULL_REGISTRATION = 'SUCCESSFULL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const CLEAN_ALERT = 'CLEAN_ALERT';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
