export const SUCCESSFULL_REGISTRATION = 'SUCCESSFULL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const LOG_OUT = 'LOG_OUT';

export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAN_ALERT = 'CLEAN_ALERT';

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';
